---
title: "GEOG 6000 01 Introduction to python lab"
author: | 
  | Simon Brewer
  | Geography Department
  | University of Utah
date: "January 14, 2021"
output:
  html_document:
    toc: true
    toc_float: true
    fig_caption: true
header-includes:
   - \usepackage{tabularx}
---

In this lab, we will introduce the basic functionality of python, together with some simple plotting functions. We will be using the following files for these examples:

- A dataset of morphological measurements of three species of penguin *penguins.csv*

More information about this dataset can be found here: [https://allisonhorst.github.io/palmerpenguins/index.html](https://allisonhorst.github.io/palmerpenguins/index.html)


# Introduction to python

Python is a high level programming language, designed for handling data (rather than software development). It is an interpreted language, which allows you to write relatively straightforward code that is then compiled in order to be run. This means that the code you write can be easily transferred between computers and operating systems, and you can just let the python interpreter on the computer do all the work for you. In contrast to other programming languages it is dynamically typed, so you don't need to track and declare all your variables, which generally means that it is easier to set up and run python code than most low-level languages (e.g. c++), but with a higher risk of encountering problems with the variables you use (although these are pretty rare). 

Python also has a large number of add-on [packages][packID] that extend the basic function, and we'll be using several of these for machine learning. Today, we'll just use a couple of these for data manipulation and plotting. 

## Getting started

For this class, the labs will assume that you have your files organized according to the following structure:

```
+-- geog5160
|   +-- datafiles
|   +-- lab01
|   +-- lab02
|   +-- lab03
...
|   +-- lab11
```

To do this, go to your `Documents` folder, and create a new folder called `geog6000`. In this now create two new folders, one called `datafiles` (where we will store all the data used across all labs and one called `lab01`, which we will use for today's lab. 

Now download the *penguins.csv* file from Canvas and move this to the `datafiles` subfolder. 
# Installing python

There are two commonly used versions of Python: 2.7 and 3. Version 3 was released in 2008 and there has been a gradual transition to only using 3 (support for 2.x was stopped in 2020). In this class, we will only use Python 3. There are several [packaged distributions][distID] of python that come with additional utilities. I would recommend using miniconda (these labs were written using this). Instructions for installing miniconda can be found [here][mcID]. 

# Using conda

## Starting python

### Windows

Open terminal???

### Mac OSX

Open any terminal. If conda has been correctly installed, you should see the following prompt

```
(base) username:
```

### Linux

Open any terminal. If conda has been correctly installed, you should see the following prompt

```
(base) username:
```

## conda environments

One of the key features of conda is the use of environments. Each environment represents an isolated python session, and so can be set up differently. This can help to avoid conflicts between add-on packages; you can create an environment for a particular type of analysis or data processing and only install the packages that you actually need. If conflicts arise, it is then easy to delete the environment and try to set it up again, all wthout impacting the base install of python. The default environment is `base` (hence the `(base)` shown before the prompt). In general, you should only install packages here if you are likely to use them a lot. Packages that are specific to a given project should only be installed in that environment. 

To create a new environment, simply type

```
conda create -n new-env
```

Python may ask you about the installation location for this environment, just accept the default. The environment will be set up then made available for use. Note that this onyl creates the environment, but you are still in the `base` environment. To change to `new-env`, type

```
conda activate new-env
```

Any you should see the prompt change from `(base)` to `(new-env)`. If you want to see a list of all the available environments:

```
conda env list
```

You can stop your current environment return to the `base` environment:

```
conda deactivate
```

And environments can be deleted as follows:

```
conda env remove -n new-env
```

### Installing packages

The `conda` command can also be used to install packages. To demonstrate this, we'll start by installing the Jupyter Noteback package. This provides an interactive framework for testing and running python code through your browser. As this is a widely used package, we'll install it in the `base` environment. Go to your terminal and enter the following code:

```
conda install -c conda-forge notebook
```

This will install `notebook` from the `conda-forge` repository. There are several repositories that host these packages, and `conda` uses anaconda.com by default. If your package is hosted elsewherem you need to specify this with the `-c` argument. The best way to find out where a particular package is held is by googling `conda install packagename` and following the links. Once you run this command, conda will check your local environment against the remote one, and download the necessary files to make the notebook work (this includes any dependencies). Once you see the following three lines, the note book is installed. 

```
  Preparing transaction: done
  Verifying transaction: done
  Executing transaction: done
```

### jupyter notebooks



[pydlID]: https://www.python.org/downloads/
[distID]: https://wiki.python.org/moin/PythonDistributions
[mcID]: https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html#
[packID]: https://wiki.python.org/moin/UsefulModules