---
title: 'GEOG 5160 6160 Spatial Data Science in Practice'
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author:
  - Simon Brewer^[University of Utah, simon.brewer@ess.utah.edu]
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: flatly
    df_print: paged
    number_sections: false
    toc: false
    toc_float: false
---

# Introduction

Spatial data science is a fast-growing discipline, with wide-ranging applications, including human health, economics, water resources, energy and food security, infrastructure, natural hazards, and biodiversity. This class is designed to provide an introduction to the methods used to work with these data, including data acquisition and manipulation, building predictive model pipelines and spatial simulation approaches. Students taking this class will learn both the theory and practice of using these methods through a combination of lecture and hand-on computer work. Over the course of the semester, students will develop their own spatial data analytical projects, which will include the design and implementation of the project as well as the communication of results. 

# Classes

- Lab 1
    - [Installation instructions][install]
    - [Lab notes (R)][lab01r]
    - [Lab notes (Python notebook)][lab01p]
    - [Lab notes (Python colab)][lab01c]
- Lab 2
    - [Lab notes (R)][lab02r]
    - [Lab notes (Python notebook)][lab02p]
    - [Lab notes (Python colab)][lab02c]
- Lab 3
    - [Lab notes (R)][lab03r]
    - [Lab notes (Python notebook)][lab03p]
    - [Lab notes (Python colab)][lab03c]
- Lab 4
    - [Lab notes (R)][lab04r]
    - [Lab notes (Python notebook)][lab04p]
    - [Lab notes (Python colab)][lab04c]
- Lab 5
    - [Lab notes (R)][lab05r]
    - [Lab notes (Python notebook)][lab05p]
    - [Lab notes (Python colab)][lab05c]
- Lab 6
    - [Lab notes (R)][lab06r]
    - [Lab notes (Python notebook)][lab06p]
    - [Lab notes (Python colab)]
- Lab 7
    - [Lab notes (R)][lab07r]
    - [Lab notes (Python notebook)][lab07p]
    - [Lab notes (Python colab)][lab07c]
- Lab 8
    - [Lab notes (R)][lab08r]
    - [Lab notes (Python notebook)][lab08p]
    - [Lab notes (Python colab)][lab08c]

# Data

- Lab 1
    - [Penguins dataset][penguins]
- Lab 2
    - [Housing dataset][housing]
- Lab 3
    - [Pinus edulis dataset][pe_df]
    - [Natural Earth coastlines][ne_shp]
    - [Current environmental data][curr_env]
    - [Future environmental data][futr_env]
- Lab 4
    - [Landslide locations from Ecuador][lslpts]
    - [Environmental data for landslide predictions][lsl_ta]
    - [Cancer mortality rates][cancer]
    - [Atlantic county shapefile][atl_shp]
- Lab 5
    - [Bike rental dataset][bike]
    - [Housing dataset][housing]
- Lab 6
    - [Gapminder dataset][gap]
    - [Natural Earth coastlines][ne_shp]
    - [Cancer mortality rates][cancer]
    - [Atlantic county shapefile][atl_shp]
- Lab 7
    - [Classification dataset][class_data]
    - [Credit dataset][credit_data]
- Lab 8
    - [EuroSAT RGB images][eurosat_rgb]
    

[install]: https://simonbrewer.github.io/geog5160/GEOG_5160_6160_Installation.html
[lab01r]: https://simonbrewer.github.io/geog5160/GEOG_5160_6160_lab01.html
[lab01p]: https://github.com/simonbrewer/geog5160/blob/main/GEOG_5160_6160_lab01.ipynb
[lab01c]: https://colab.research.google.com/drive/18oHWVeZJs-tHIkNGjsHMOtx0IVGZtlec?usp=sharing
[lab02r]: https://simonbrewer.github.io/geog5160/GEOG_5160_6160_lab02.html
[lab02p]: https://github.com/simonbrewer/geog5160/blob/main/GEOG_5160_6160_lab02.ipynb
[lab02c]: https://drive.google.com/file/d/1v6cTv3zA1YH7yvZHitBL5dstYRUgxOZq/view?usp=sharing
[lab03r]: https://simonbrewer.github.io/geog5160/GEOG_5160_6160_lab03.html
[lab03p]: https://github.com/simonbrewer/geog5160/blob/main/GEOG_5160_6160_lab03.ipynb
[lab03c]: https://drive.google.com/file/d/1SlhPrshvdMKUpi0gfmEobvlNwGuZmmec/view?usp=sharing
[lab04r]: https://simonbrewer.github.io/geog5160/GEOG_5160_6160_lab04.html
[lab04p]: https://github.com/simonbrewer/geog5160/blob/main/GEOG_5160_6160_lab04.ipynb
[lab04c]: https://colab.research.google.com/drive/11buvWJVZ3GPZasCv0wNlfqSzjLreTEQA?usp=sharing
[lab05r]: https://simonbrewer.github.io/geog5160/GEOG_5160_6160_lab05.html
[lab05p]: https://github.com/simonbrewer/geog5160/blob/main/GEOG_5160_6160_lab05.ipynb
[lab06r]: https://simonbrewer.github.io/geog5160/GEOG_5160_6160_lab06.html
[lab06p]: https://github.com/simonbrewer/geog5160/blob/main/GEOG_5160_6160_lab06.ipynb
[lab07r]: https://simonbrewer.github.io/geog5160/GEOG_5160_6160_lab07.html
[lab07p]: https://github.com/simonbrewer/geog5160/blob/main/GEOG_5160_6160_lab07.ipynb
[lab07c]: https://colab.research.google.com/drive/1Pjedvyh7aGc1NL6b1aRkUTfYRgyA0NyV?usp=sharing
[lab08r]: https://simonbrewer.github.io/geog5160/GEOG_5160_6160_lab08.html
[lab08p]: https://github.com/simonbrewer/geog5160/blob/main/GEOG_5160_6160_lab08.ipynb
[lab08c]: https://colab.research.google.com/drive/1Pjedvyh7aGc1NL6b1aRkUTfYRgyA0NyV?usp=sharing

[penguins]: https://drive.google.com/file/d/1Sb5uv2RP_gcNJDKmlEjBoSUOdETIq2Jf/view?usp=sharing
[housing]: https://drive.google.com/file/d/1pTBKamvTk7ZLsRIFKRNQ37_XU2J5y9XT/view?usp=sharing
[pe_df]: https://drive.google.com/file/d/1YUML4HEX1jLgpuiODJNMrxKlru8tCKJe/view?usp=sharing
[ne_shp]: https://drive.google.com/file/d/1IF2GT05HggO2OncDbDnp9ZF1toggj54r/view?usp=sharing
[curr_env]: https://drive.google.com/file/d/1tuyY7VFgkXWvppMwpTxYl-34lYa_4pyL/view?usp=sharing
[futr_env]: https://drive.google.com/file/d/1at_RvzwRTVdiFInV03hXOuvvfeo1iJjv/view?usp=sharing
[atl_shp]: https://drive.google.com/file/d/123_jTvrCbA80Gl0GmKCmLylB5RZf-1_5/view?usp=sharing
[cancer]: https://drive.google.com/file/d/1cgplF41EKtQ32vkDOf-y1W9lnwbAGg_u/view?usp=sharing
[lslpts]: https://drive.google.com/file/d/1x9bZXR86J-kFxufFvmNpbrid66krbONI/view?usp=sharing
[lsl_ta]: https://drive.google.com/file/d/1DO6eyL-N48rM-2pU4ddwMn4YFRoouYtM/view?usp=sharing
[bike]: https://drive.google.com/file/d/1vuFJPShROaRHSc_rJrRkskTiIQONjLzk/view?usp=sharing
[gap]: https://drive.google.com/file/d/1KKqQFDBv8Axditeo95wgRECrA9jCPchD/view?usp=sharing
[class_data]: https://drive.google.com/file/d/1282606hbmX2UuBd6IoKpXQy9TbS3-yZ7/view?usp=sharing
[credit_data]: https://drive.google.com/file/d/13dbnHh0VMEb8dlTf-YU6CJC4tday8L6V/view?usp=sharing
[eurosat_rgb]: https://drive.google.com/file/d/1jxJHZkAwrlyP-YZ4vRsYS7KVltp5-4yQ/view?usp=sharing