---
title: "GAP Minder SOM"
author: "Simon Brewer"
date: "4/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rgdal)
library(dplyr)
library(tmap)
library(ggpubr)
library(kohonen)
library(gapminder)
library(RColorBrewer)
```

## Data

```{r}
data(gapminder)
head(gapminder)
```

```{r}
gapminder %>%
  filter(country == "United States") %>%
  ggline(x = "year", y = "pop") + ggtitle("U.S. Population (GAP)")
```

```{r}
gapminder %>%
  filter(country == "United States") %>%
  ggline(x = "year", y = "gdpPercap") + ggtitle("U.S. per capita GDP (GAP)")
```

```{r}
gapminder %>%
  filter(country == "United States") %>%
  ggline(x = "year", y = "lifeExp") + ggtitle("U.S. life expectancy (GAP)")
```

```{r}
gapminder %>%
  gghistogram(x = "pop")

gapminder %>%
  gghistogram(x = "lifeExp")

gapminder %>%
  gghistogram(x = "gdpPercap")
```


## Transform variables

```{r}
gap2.df = gapminder %>%
  mutate(lpop = log(pop),
         llifeExp = log(lifeExp),
         lgdpPC = log(gdpPercap)) %>%
  filter(year == 2007) %>%
  select(country, year, lpop, llifeExp, lgdpPC)
head(gap2.df)
```


## SOM

Set up SOM grid

```{r}
mygrid = somgrid(xdim = 8, ydim = 7, topo = "hexagonal")
plot(mygrid)
```

Run SOM with defaults
```{r}
gap.som = som(scale(gap2.df[,3:5]), mygrid, rlen = 2000)
gap.som
```

### Plots

1. Loss function

```{r}
plot(gap.som, type = "changes")
```

2. U-matrix

```{r}
plot(gap.som, type = "dist")
```

3. Counts

```{r}
plot(gap.som, type = "counts")
```

4. Codebook

```{r}
plot(gap.som, type = "code")
```

5. Individual codes

```{r}
plot(gap.som, type = "property", property = gap.som$codes[[1]][,1],
     main = "Pop")
```

```{r}
plot(gap.som, type = "property", property = gap.som$codes[[1]][,2],
     main = "Life Exp.")
```

```{r}
plot(gap.som, type = "property", property = gap.som$codes[[1]][,3],
     main = "GDP Per Cap.")
```

### Cluster analysis

```{r}
som_cluster <- cutree(hclust(dist(gap.som$codes[[1]])), 6)
mypal = brewer.pal(6, "Set2")
# plot these results:
plot(gap.som, type="mapping", bgcol = mypal[som_cluster], 
     main = "Clusters", pch = '.') 
add.cluster.boundaries(gap.som, som_cluster)
```


## Plot all countries

```{r}
country.pos = mygrid$pts[gap.som$unit.classif,]
country.crds = aggregate(country.pos, by = list(gap2.df$country), mean)
plot(gap.som, type="mapping", labels = abbreviate(country.crds[,1], 6),
     bgcol = mypal[som_cluster], 
     main = "Clusters", cex = 0.5, keepMargins=TRUE) 
add.cluster.boundaries(gap.som, som_cluster)
```

## Maps

Get world shapefile

```{r}
borders = readOGR("~/Dropbox/Data/NaturalEarth/50m_cultural/ne_50m_admin_0_countries.shp")
```

```{r}
library(countrycode)
gap2.df$cluster = as.factor(som_cluster[gap.som$unit.classif])

df <- gap2.df %>% 
  mutate(ISO3 = countrycode(country, "country.name", "iso3c"))

cluster.sp = sp::merge(borders, df, by.x = "adm0_a3", by.y = "ISO3",
                      duplicateGeoms = TRUE)
```

```{r}
tm_shape(cluster.sp) + tm_fill("cluster", palette = "Set2")
```